### ISSUE TITLE
Bot doesn't leave channel

### ISSUE THREAD

**Issue by SRLJustin** [Armored-Dragon/goldmine#3]
When using the 'play' command to listen to a song from YouTube, once the song has finished (or the queue is empty) the bot will just idle in the voice channel and not part.

If another user in a different voice channel requests a song, the bot will not move the channel where the user requested the song from.

If the bot is idling in VoiceChannel1 and someone in VoiceChannel2 attempts to move the bot by using the 'summon' command, the error is shown:

justin: >summon
BOTS: An internal error occured while responding to >summon!
ClientException: Already connected to a voice channel in this server

**Comment by Armored-Dragon** [comment]
I just tested this in my production (public) copy, it appears to work (the moving channels). Maybe I fixed it recently during the voice revamp. This is why you update your bot often with the `>update` command 😉 
As for the idling, that's a planned fix and should come tomorrow.

**Comment by SRLJustin** [comment]
The switching of channels is working with a fresh update of the bot, thanks for that.

Just the bot idling in the channel is still a bug

**Comment by SRLJustin** [comment]
Any updates on getting the bot to leave the voice channel when the queue is finished?

**Comment by Armored-Dragon** [comment]
Yes, it's not immediate but should do it within 5 minutes.

**Comment by SRLJustin** [comment]
Unfortunately with release v2.2.1 it seems to be indefinite

**Comment by Armored-Dragon** [comment]
The releases are terribly outdated. Just use master.

**Comment by SRLJustin** [comment]
Thanks, I'll migrate to the master branch.
