### ISSUE TITLE
Bot crashes when 'stop' command executed

### ISSUE THREAD

**Issue by SRLJustin** [Armored-Dragon/goldmine#5]
When executing the 'stop' command and the bot is in a voice channel, the bot will crash

>Traceback (most recent call last):
>  File "C:/Users/Justin/PycharmProjects/goldmine/goldmine.py", line 40, in <module>
>    retval = core.main(use_uvloop)
>  File "C:\Users\Justin\PycharmProjects\goldmine\core.py", line 76, in main
    runbot(loop, bot)
  File "C:\Users\Justin\PycharmProjects\goldmine\core.py", line 41, in runbot
    loop.run_until_complete(bot.start(bot_token))
  File "C:\Users\Justin\AppData\Local\Programs\Python\Python35\lib\asyncio\base_events.py", line 325, in run_until_complete
    self.run_forever()
  File "C:\Users\Justin\AppData\Local\Programs\Python\Python35\lib\asyncio\base_events.py", line 295, in run_forever
    self._run_once()
  File "C:\Users\Justin\AppData\Local\Programs\Python\Python35\lib\asyncio\base_events.py", line 1218, in _run_once
    event_list = self._selector.select(timeout)
  File "C:\Users\Justin\AppData\Local\Programs\Python\Python35\lib\selectors.py", line 314, in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
  File "C:\Users\Justin\AppData\Local\Programs\Python\Python35\lib\selectors.py", line 305, in _select
    r, w, x = select.select(r, w, w, timeout)
OSError: [WinError 10038] An operation was attempted on something that is not a socket

Process finished with exit code 1

Running Win 10 64bit - I've drilled down and found the bug to be this function:

C:/Users/Justin/AppData/Local/Programs/Python/Python35/Lib/site-packages/discord/voice_client.py

```ruby
   @asyncio.coroutine
    def disconnect(self):
        """|coro|

        Disconnects all connections to the voice client.

        In order to reconnect, you must create another voice client
        using :meth:`Client.join_voice_channel`.
        """
        if not self._connected.is_set():
            return

        self._connected.clear()
        try:
            yield from self.ws.close()
            yield from self.main_ws.voice_state(self.guild_id, None, self_mute=True)
        finally:
            self.socket.close()
```

self.socket.close() seems to be causing the issue. Not sure if there is much you can do as it's in the discord package

**Comment by Armored-Dragon** [comment]
Can you check if `C:/Users/Justin/AppData/Local/Programs/Python/Python35/Lib/site-packages/discord/voice_client.py` has a definition of `class VoiceClientProtocol(asyncio.Protocol)` right above `class VoiceClient`?

**Comment by SRLJustin** [comment]
Yes, it's there

```python
class VoiceClientProtocol(asyncio.Protocol):
    def __init__(self, secret_key, callback):
        self.callback = callback
        self.box = nacl.secret.SecretBox(bytes(secret_key))
        super().__init__()

    def datagram_received(self, data, addr):
        """
        Decrypt the data before passing it to the callback
        """
        nonce = bytearray(24)
        nonce[:12] = data[:12]
        sequence, timestamp, ssrc = struct.unpack_from('>2xHII', data)
        self.callback(self.box.decrypt(data[12:], nonce=bytes(nonce)), ssrc, sequence, timestamp)

class VoiceClient:
```

**Comment by Armored-Dragon** [comment]
Just reinstall discord.py and it should work fine.
